name: Clang-Tidy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  static-analysis:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"
          directory: ${{github.workspace}}/llvm

      - name: Check
        run: ${{github.workspace}}/ci-check.sh analyze
        env:
          CC: clang
          CXX: clang++
          CMAKE_BUILD_TYPE: Debug
